[server]
address = "localhost"
port = 5000
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#b80e0e"  # Witcher red
backgroundColor = "#1a1a1a"  # Dark background
secondaryBackgroundColor = "#2d2d2d"  # Slightly lighter dark
textColor = "#ffffff"  # White text
font = "sans serif"

[browser]
serverAddress = "localhost"
serverPort = 5000
gatherUsageStats = false